Update zsh completions

diff --git a/home/dot_config/zsh/completions/_hk b/home/dot_config/zsh/completions/_hk
--- a/home/dot_config/zsh/completions/_hk
+++ b/home/dot_config/zsh/completions/_hk
@@ -1,9 +1,9 @@
-#compdef mise
+#compdef hk
 # @generated by usage-cli from usage spec
 local curcontext="$curcontext"
 
 # caching config
-_usage_mise_cache_policy() {
+_usage_hk_cache_policy() {
   if [[ -z "${lifetime}" ]]; then
     lifetime=$((60*60*4)) # 4 hours
   fi
@@ -12,21 +12,19 @@ _usage_mise_cache_policy() {
   (( $#oldp ))
 }
 
-_mise() {
+_hk() {
   typeset -A opt_args
   local curcontext="$curcontext" cache_policy
 
   if ! type -p usage &> /dev/null; then
       echo >&2
-      echo "Error: usage CLI not found. This is required for completions to work in mise." >&2
+      echo "Error: usage CLI not found. This is required for completions to work in hk." >&2
       echo "See https://usage.jdx.dev for more information." >&2
       return 1
   fi
 
-  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_mise_2026_3_13.spec"
-  if [[ ! -f "$spec_file" ]]; then
-    mise usage >| "$spec_file"
-  fi
+  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_hk.spec"
+  hk usage >| "$spec_file"
   local -a completions=()
   while IFS= read -r line; do
     completions+=("$line")
@@ -35,10 +33,10 @@ _mise() {
   return 0
 }
 
-if [ "$funcstack[1]" = "_mise" ]; then
-    _mise "$@"
+if [ "$funcstack[1]" = "_hk" ]; then
+    _hk "$@"
 else
-    compdef _mise mise
+    compdef _hk hk
 fi
 
 # vim: noet ci pi sts=0 sw=4 ts=4
