Add live-command.nvim and vim-fugitive

diff --git a/.config/git/templates/hooks/prepare-commit-msg b/.config/git/templates/hooks/prepare-commit-msg
--- a/.config/git/templates/hooks/prepare-commit-msg
+++ b/.config/git/templates/hooks/prepare-commit-msg
@@ -1,10 +1,21 @@
 #!/usr/bin/env bash
 
-BRANCH=$(git branch | grep '^\*' | cut -b3- | cut -f1,2 -d'-')
-BRANCHTYPE=${BRANCH%/*}
-FILE=$(cat "$1")
+# check if inside a git repository
+if ! git rev-parse --git-dir >/dev/null 2>&1; then
+    echo "Error: Not inside a Git repository." >&2
+    exit 1
+fi
 
-FIRSTLINE=$(sed -n "1p" "$1")
-if [[ -z $FIRSTLINE ]]; then
-    echo -e "$BRANCHTYPE: $FILE" >"$1"
+CURRENT_BRANCH=$(git branch --show-current)
+
+# extract BO-XXXXX pattern (5 digits)
+if echo "$CURRENT_BRANCH" | grep -qE 'BO-[0-9]{5}'; then
+    PREFIX="$(echo "$CURRENT_BRANCH" | sed -n 's/.*\(BO-[0-9]\{5\}\).*/[\1]/p')"
+else
+    PREFIX=""
+fi
+
+FILE=$(cat "$1")
+if [[ ! -z "$PREFIX" ]]; then
+    echo -e "$PREFIX: $FILE" >"$1"
 fi
