Make zsh function posix

diff --git a/home/dot_config/zsh/functions/dai b/home/dot_config/zsh/functions/dai
--- a/home/dot_config/zsh/functions/dai
+++ b/home/dot_config/zsh/functions/dai
@@ -1,9 +1,30 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-# Select a docker container to start and attach interactively to it
-function dai() {
-  local cid
-  cid=$(docker ps | sed 1d | fzf -1 -q "$1" | awk '{print $1}')
+# Select a running docker container and attach interactively to it
+dai() {
+  if ! docker ps -q | grep -q .; then
+    echo "No docker containers running!"
+    return 1
+  fi
 
-  docker exec -it "$cid" sh -c "if [ -x /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi"
+  if [ -n "$1" ]; then
+    _cid="$(docker ps -q --filter "name=$1" | head -n1)"
+  else
+    _cid="$(
+      docker ps --format "{{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}" |
+        fzf -1 |
+        awk '{print $1}'
+    )" || return 1
+  fi
+
+  if [ -z "$_cid" ]; then
+    echo "Couldn't find container id"
+    return 1
+  fi
+
+  docker exec -it "$_cid" sh -c "if [ -x /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi"
+
+  unset _cid
+
+  return 0
 }
